### ISSUE TITLE
Shut down a node when its job is done.

### ISSUE THREAD

**Issue by PGijsbers** [openml/automlbenchmark#10]
Currently, nodes only get terminated if the whole chunk is done, if there is a straggler, other nodes will keep running for the same amount of time. It's not a big deal (as there is a timelimit on the stragglers anyway), but it would be a nice improvement.

**Comment by PGijsbers** [comment]
@seb-h2o I think this is no longer the case, right?

**Comment by seb-h2o** [comment]
@PGijsbers correct, nodes are now terminated about 1mn after their job completion.
