### ISSUE TITLE
TunedRandomForest is having incorrect venv setting?

### ISSUE THREAD

**Issue by franchuterivera** [openml/automlbenchmark#103]
In TunedRandomForest following line is not properly allowing venv to work:

https://github.com/openml/automlbenchmark/blob/1c1559c28540b8bd8c0cd5ee6b44786f3c601a8e/frameworks/TunedRandomForest/setup.sh#L3

It should be something like this right:
. $HERE/../shared/setup.sh $HERE

**Comment by PGijsbers** [comment]
Thanks!
