### ISSUE TITLE
Support for Framework overwrites 

### ISSUE THREAD

**Issue by franchuterivera** [openml/automlbenchmark#106]
This question is in the context of testing how a framework-specific feature performs in the benchmark.

For example, in autosklearn it would be useful to compare what is the effect of turning on a new API setting. You can, of course, change the exec.py, then rebuild any docker/singularity images, and test. Yet, doing so is very time-consuming.

Do you have any recommendations on how to tweak a framework's setting and have the containers properly process it?

Example: It would be really nice if we could provide a command-line overwrites to the runbenchmark.py (which will be given to the actual the actual framework eventually) -- if you think this will be useful fo you, we already have something that provides command-line overwrites through the TaskConfig so that is up to the framework to use it. But if there is a better way, please let us know.

**Comment by PGijsbers** [comment]
If I'm not mistaken, specifying the parameters in the [frameworks.yaml](https://github.com/openml/automlbenchmark/blob/master/resources/frameworks.yaml#L42) file should work. Just make sure to read out the settings [like](https://github.com/openml/automlbenchmark/blob/master/frameworks/TunedRandomForest/exec.py#L38 [so](https://github.com/openml/automlbenchmark/blob/master/frameworks/TunedRandomForest/exec.py#L84).

**Comment by sebhrusen** [comment]
@franchuterivera proper way run frameworks with custom parameters is described in the `frameworks.yaml` example in this section: https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#framework-definition

There is also support to override those parameters directly in the command line, but I would not recommend it, except for trying sth quickly locally: for example:
```
python runbenchmark.py randomforest -Xf.n_estimators=500
```
will pass the param `n_estimators=500` to the framework (here RandomForest)
The problem with this approach is that currently the parameters don't appear in the results file, which prevents from analyzing the results correctly, and as such I need to fix this.

**Comment by franchuterivera** [comment]
I see, thanks! -Xf.n_estimators=500 sounds exactly what I was looking for. I do understand what you say with the results, would take that into consideration... but it if you could enhance the result file format it would be appreciated. 

Thanks!

**Comment by sebhrusen** [comment]
looking into it if there's an easy fix

**Comment by sebhrusen** [comment]
I forgot to mention: the command line approach will work only in `local` mode: this is not propagated to docker or ec2 instances.
If you need a support that works also for those, then the framework definition (using `extends`) as mentioned above is the only solution.

**Comment by franchuterivera** [comment]
I see, thanks for the suggestion!
But then I have one question... you do have to build the docker image every time you do that right?

I just tried:

1. Cloning automlbenchmark repo
2. Creating an autosklearn image for docker via -m docker -s force
3.Updating the framework for  a new extension such as:
`
autosklearn_meta:
   extends: autosklearn
   params:
     initial_configurations_via_metalearning: 5 
`
This point 3, I tried using the -u option, ~/.config/automlbenchmark/frameworks.yaml but they all error due to:

ERROR:
Incorrect framework `autosklearn_meta`: not listed in /bench/resources/frameworks.yaml.

For your comment:
`If you need a support that works also for those, then the framework definition (using extends) as mentioned above is the only solution.`

is there something that I am missing apart from the -u option?

**Comment by sebhrusen** [comment]
>  But then I have one question... you do have to build the docker image every time you do that right?

no, you only need to rebuild the docker image when there is a change in your setup (new framework version, dependency...).
The `params` section in the framework definitions is dynamic, and only used at runtime, not during the setup phase.
That's why, once you have a framework module (`frameworks.autosklearn`, frameworks.H2OAutoML`, ...) you can have as many definitions as you want.
Also, if you use`extends` it will automatically inherit the image definition from its parent.

For example, given:
```
autosklearn:
  version: '0.6.0'
  project: https://automl.github.io/auto-sklearn/stable/
```
with associated docker image `automlbenchmark/autosklearn:0.6.0-stable`, then
```
autosklearn_nometa:
  extends: autosklearn
  params:
    initial_configurations_via_metalearning: 0
```
will use the same autosklearn docker image,  when running:
> python runbenchmark.py autosklean_nometa -m docker

To get this to work, you need to a custom `config.yaml` similar to this one: https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#custom-configuration
so that the docker image can read your custom `frameworks.yaml` (remember that all those custom frameworks definition should not reside in the default `frameworks.yaml` but in your custom one).

**Comment by franchuterivera** [comment]
Ah, I see!
everything is working now... thanks for the help!
