### ISSUE TITLE
Links in Readme.md not working

### ISSUE THREAD

**Issue by flokde** [openml/automlbenchmark#112]
Some of the links lead to 404 - Page not found:

Features
...
- **New AutoML systems can be added** as Docker images
...

Installation:
...
- The Python libraries listed in **requirements.txt**:
...

Quickstart:
...
- The AutoML framework that should be evaluated, see **frameworks.yaml** for supported frameworks. If you want to add a framework see **here**.
- The benchmark suite to run should be one implemented **in benchmarks folder**.
...

Thanks for the great work! Love the idea behind the project!

**Comment by sebhrusen** [comment]
@flokde thanks for noticing and listing those links. Most links got broken after moving the README.md under `docs` folder.
Fixing those now.
