### ISSUE TITLE
Expose data as pandas Dataframes instead of numpy arrays.

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#116]
Currently, data can be accessed by frameworks either as a raw file (ARFF file when using OpenML, ARFF or CSV when using explicit file), or as a `numpy` array.

Frameworks that can load raw files directly can use their own logic to identify columns types.
For others, the application offers the `data_type` attribute for each feature, but due to the various data loaders, there are some inconsistencies in the type names for historical reasons, and even in the type mapping (openML loader keeps string columns as `string` whereas the file loader considers them as `categorical`).

## Proposal 1:
select a list of types and use only those from 'amlb.data' module, loaders are responsible to ensure that format specific types get converted to one in this list.
For example: categorical, string, integer, real, boolean, datetime.

## Proposal 2:
embrace `pandas` DataFrames instead of `ndarray` (in `amlb.data.DataSplit`): will probably require small changes for each framework integration.
Would be good for a v2.0.

# Conclusion
Proposal 2 it will be

**Comment by Innixma** [comment]
I'm in favor of Proposal 2, unless there are frameworks that require or gain benefits from Proposal 1. `pandas DataFrame` are much less prone to having strange things happen with them regarding dtypes than `numpy ndarray` in my experience, and if necessary, the inner `numpy ndarray` can be accessed from the `pandas DataFrame` object.

**Comment by sebhrusen** [comment]
To anyone interested, I'm about to spend some effort on this: frameworks will be able to directly ingest pandas dataframes instead of numpy arrays and therefore support all types supported by pandas.
