### ISSUE TITLE
Incorporating code changes in AWS mode runs

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#142]
Is it possible for the EC2 instances to use the automlbenchmark code present on the machine executing the runbenchmark.py -m aws?

Currently it seems that it clones mainline, which means I need to do config edits in ~/.config/automlbenchmark/ to get my changes recognized, which is a bit cumbersome. This also makes it hard to genuinely test old versions of automlbenchmark code since it will still clone mainline on the EC2 instances.

An alternative solution could be to (optionally) upload the local automlbenchmark code to the designated s3 bucket and sync those s3 files onto the EC2 instance as opposed to git cloning. This could be done on the original runbenchmark.py call when the ec2/user/ files are being copied into the bucket.

**Comment by sebhrusen** [comment]
Hi @Innixma
EC2 instances clone the branch tagged as `stable` by default, it's not even the HEAD.
see the default `resources/config.yaml`
```
project_repository: https://github.com/openml/automlbenchmark#stable      # this is also the url used to clone the repository on ec2 instances
                                                                          # when running those without docker.
                                                                          # to clone a specific branch/tag, add a url fragment, e.g.:
                                                                          # https://github.com/openml/automlbenchmark#stable
```

therefore you can easily tell it to clone any branch or tag, that's actually how I test fix/feature branches.
for example, if your custom `config.yaml` contains:
```
project_repository: https://github.com/openml/automlbenchmark
```
then it will clone the HEAD from master branch,

if it contains
```
project_repository: https://github.com/openml/automlbenchmark#my_branch
```
then it will clone `my_branch`.
Of course, it can also point to a fork repo.

I hope this enough for your needs.

**Comment by Innixma** [comment]
Thanks for the helpful reply! I was able to specify a forked repo/branch to get things working as intended on AWS.
