### ISSUE TITLE
can automlbenchmark specify only one algorithm to make comparison?

### ISSUE THREAD

**Issue by ajoeajoe** [openml/automlbenchmark#146]
Specific only one algorithm, like SVM, and then make a comparison of different AUTOML ( autosklearn, h2o and so on), thanks.

**Comment by PGijsbers** [comment]
Hi ajoeajoe,

If I understand correctly, you are asking if it is possible to compare the different AutoML methods if they would only consider one type of learning algorithm, which means configuring the search space of the AutoML framework(s). This is (currently) not possible out of the box. 

If you're really interested in this, you could achieve this by manually editing each of the [AutoML Framework wrappers](https://github.com/openml/automlbenchmark/tree/master/frameworks). For example, with TPOT you would need to adjust [this file](https://github.com/openml/automlbenchmark/blob/master/frameworks/TPOT/exec.py). You'd need to define the search space yourself with the specification set by the package frameworks (for TPOT, [explicitly set the `config_dict`](https://epistasislab.github.io/tpot/api/)).
I don't know if all frameworks support this, but I think most do.

If you're asking if it is possible to compare the AutoML systems to a single algorithm, like we did in the paper to a RandomForest, then this is currently only possible if you wrap the algorithm like we did for the [RandomForest](https://github.com/openml/automlbenchmark/tree/master/frameworks/RandomForest). If you want to compare to a single algorithm, there are several questions which you would need to think of, for example:
 - Does the algorithm deal with missing values? If not, how do you deal with missing values in the data?
 - Does the algorithm deal with non-numeric data? If not, how do you deal with non-numeric data?
 - Do you only consider a single hyperparameter configuration for the algorithm, if so, which? If not, which configurations do you want to try and in which order?

**Comment by sebhrusen** [comment]
> If you're really interested in this, you could achieve this by manually editing each of the AutoML Framework wrappers. For example, with TPOT you would need to adjust this file. You'd need to define the search space yourself with the specification set by the package frameworks (for TPOT, explicitly set the config_dict).
I don't know if all frameworks support this, but I think most do.

Technically, you don't need to edit the wrapper, you can just add a framework definition (following instructions in https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#framework-definition) :
```
TPOT_myconfig:
   extends: TPOT
   description: "run TPOT only with SVM algo"
   params:
     config_dict: { ... }
```

then you can run 
> python runbenchmark.py tpot_myconfig
instead of
> python runbenchmark.py tpot

**Comment by PGijsbers** [comment]
Thanks! I forgot about that, though I suppose it relies on the framework allowing you to set the search space through it's initialization arguments? That might be all Python frameworks though, not sure.

**Comment by ajoeajoe** [comment]
Thanks , @PGijsbers and @sebhrusen , I means that run automl with only specific algo, like @sebhrusen  says "run TPOT only with SVM algo", its like autosklearn can include only some algorithms, it is appreciate that if offer an example for this use.

**Comment by ajoeajoe** [comment]
I also want to know hyperoptsklearn with which Cash methods? 

as hyperopt support three methods Currently

Random Search
Tree of Parzen Estimators (TPE)
Adaptive TPE

infact, hyperoptsklearn' result is not good, I wonder if I can change its Cash method to run it.

**Comment by ajoeajoe** [comment]
I have see that you use tpe, thanks:

https://github.com/openml/automlbenchmark/blob/master/frameworks/hyperoptsklearn/exec.py

**Comment by sebhrusen** [comment]
@ajoeajoe that's a good point for Hyperoptsklearn, we did change the default `algo` there, which is wrong... (hyperopt default is `rand.suggest`). Let me fix this. I'll also provide a way to externalize this algo.

**Comment by sebhrusen** [comment]
Closing this ticket: the `hypertoptsklearn` issue is fixed with https://github.com/openml/automlbenchmark/pull/148
`hypertoptsklearn` now striclty use defaults (esp. default `algo` is random search), like for other frameworks.
See the PR above for an example of framework definition if you want to run it with a different parameters.
