### ISSUE TITLE
About the time cost metric of every "run" on openml platform

### ISSUE THREAD

**Issue by ajoeajoe** [openml/automlbenchmark#151]
is it OpenML platform dose not record the experiment(like one run) time?

for example if I want to see this run_id = 9029596 as the flowing site, how should I do?

https://www.openml.org/r/9029596

it seems you did't give any API?

**Comment by sebhrusen** [comment]
Hi @ajoeajoe, I think you're looking at the wrong project.
Looks like what you need is the `openml` API: https://docs.openml.org/APIs/
See:
https://openml.github.io/openml-python/develop/api.html#openml-runs-run-functions

**Comment by ajoeajoe** [comment]
@sebhrusen thanks, but I still can not get information about running time
>>> openml.runs.get_run(9029596)
<openml.runs.run.OpenMLRun object at 0x10fcd8438>

**Comment by PGijsbers** [comment]
Hi @ajoeajoe,
That question is better asked at the openml-python Github: https://github.com/openml/openml-python
But I'll (try to) answer your question here for now.
First, I want to note that runtime is not available for each run as it is not required to be recorded.
Second, unfortunately the current way to access it is not fleshed out.
```
r = openml.runs.get_run(9029596)
r.fold_evaluations["usercpu_time_millis_training"]
```
Shows you training time per fold. You'll also find other recordings such as test time or total time.
In general the name for the dictionary entry depends on how the user specifies it. Though for automated runs (i.e. ran through `run_model_on_task`, the same names are used).

For the AutoML benchmark, these times are not recorded (yet). We're working on better integration. However you can find the time limit set for the run:

```
r = openml.runs.get_run(10364117)
f = openml.flows.get_flow(r.flow_id)
f.parameters
```
Shows the cores, memory (in Gb) and time (in minutes), set as limits for the framework.

**Comment by ajoeajoe** [comment]
@PGijsbers PG  Many thanks for your kindly reply, I see I think what you guys working on is very meaningful.
