### ISSUE TITLE
Provide frameworks definition file with only true latest versions.

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#160]
For users who always want to benchmark some frameworks against the latest version/nightly build, we can provide a `frameworks_latest.yaml` definitions file.
On top of this, we can also start keeping for example a quarterly history of framework versions, allowing users to rerun older versions more easily and analyse progress.

---
From a conversation in https://github.com/openml/automlbenchmark/pull/159

> We could alternatively also have the frameworks at "latest", and just generate a snapshot benchmark definition every few months with fixed versions.

I like the idea, it would also allow users to (re)run older benchmarks easily as we would add a version of `frameworks.yaml` per quarter let's say. Although, for a minimum of stability and as the frameworks are always read from `frameworks.yaml` by default, I would keep the default `frameworks.yaml` with stable versions. Would you be ok with that?
```
frameworks.yaml  # current stable versions
frameworks_latest.yaml  # all frameworks set to latest (may be pulled directly from `master` branch)
frameworks_2020_Q1.yaml
frameworks_2020_Q2.yaml
...
```

So to use latest for example, user would have to run for example
```
python runbenchmark.py resources/frameworks_latest.yaml#mljarsupervised
```
but the default
```
python runbenchmark.py mljarsupervised
```
would still use the default and stable version from `frameworks.yaml`.
I can create a ticket for that, as you can see, if we want to make the switch easy, it requires some changes in how the `framework` parameter is handled to select the alternative `yaml` definition: either by overloading the syntax on the current param (as we do now for benchmarks), or by adding a new param. Personally, I tend to prefer overloading in this situation...

Well, just realized, it may already work using:
```
python runbenchmark.py mljarsupervised -Xframeworks.definition_file=resources/frameworks_latest.yaml
```
(the configuration is very flexible when using the `-X` magic)
I would need to try it.

**Comment by sebhrusen** [comment]
@PGijsbers If you have any suggestion, let's continue the discussion on this ticket.

**Comment by PGijsbers** [comment]
The only addition I have is that in the structure:

```
frameworks.yaml  # current stable versions
frameworks_latest.yaml  # all frameworks set to latest (may be pulled directly from `master` branch)
frameworks_2020_Q1.yaml
frameworks_2020_Q2.yaml
...
```

I think it would be sufficient if `frameworks.yaml` just uses the latest snapshot definition (e.g. `frameworks_2020_Q2.yaml` if that is most recent). Manually updating versions for frameworks will be very tedious and time consuming if we have to do that more frequently than every three months. If we manage to have a stable quarterly definition, then using `latest` in most cases probably won't break (much).

**Comment by PGijsbers** [comment]
And of course anytime you want to run a benchmark for e.g. a research paper, and want to ensure latest versions are used, one should make a definition with explicit versions. But I think that this does not influence the general structure we propose here.

**Comment by sebhrusen** [comment]
https://github.com/openml/automlbenchmark/issues/160#issuecomment-670843890

@PGijsbers I fully agree with you here, we don't want to spend too much time updating versions.
In the sample structure above, I was suggesting that we're in the middle of Q3 for example, and during this period, various frameworks can get updated (through PRs from owner, or quickly from us if it is as easy as just changing the version number), and at the end of Q3, the status of `frameworks.yaml` is frozen to produce `frameworks_2020_Q3.yaml` and so on.
To be clear, when writing `frameworks.yaml  # current stable versions`, I don't mean that as soon as a framework releases a new version, it should systematically be reflected in this file.

**Comment by PGijsbers** [comment]
But there are no guarantees on how often `frameworks.yaml` is updated right (other than quarterly)?
Changes can be made like you suggested, but from our side we only promise to check the framework versions at least quarterly?

**Comment by sebhrusen** [comment]
> But there are no guarantees on how often frameworks.yaml is updated right (other than quarterly)?
> Changes can be made like you suggested, but from our side we only promise to check the framework versions at least quarterly?

Yes, that's what I had in mind. Sounds reasonable? That's something we could start this quarter.

**Comment by PGijsbers** [comment]
I think that sounds reasonable 👍 I guess a todo list would be:
 - [ ] verify the latest versions for each framework, save the definition to `frameworks.yaml` and `frameworks_2020_Q3.yaml`. (note: we probably should contact Matthias on which auto-sklearn version to include, or we include both)
 - [ ] add a `frameworks_latest.yaml` with versions set to `latest`
 - [ ] update [add framework docs](https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#add-an-automl-framework), to add to both `frameworks.yaml` and `frameworks_latest.yaml` if you're shooting for a PR, and say any later version updates should in `frameworks.yaml` only.

**Comment by PGijsbers** [comment]
Actually, if there are major changes to AutoML frameworks, outdated framework definitions won't help.
You would need to specifically use the older version of the FRAMEWORK script.
I suppose we can just tag a commit every quarter, but then there is no need for different `framework.yaml` files (other than `_latest` and regular).
This would make it more inconvenient to run older versions that don't have changes to the FRAMEWORK script however.

**Comment by sebhrusen** [comment]
> Actually, if there are major changes to AutoML frameworks, outdated framework definitions won't help.
You would need to specifically use the older version of the FRAMEWORK script.
I suppose we can just tag a commit every quarter, but then there is no need for different framework.yaml files (other than _latest and regular).
This would make it more inconvenient to run older versions that don't have changes to the FRAMEWORK script however.

@PGijsbers Totally agree, the merged PR supports both currently as we will still need to create a specific framework definition file before official runs, now that the app uses the latest release by default.
But it also implements the versioning workflow on GitHub that we now need to use for every release.

`the frameworks_2020Q2.yaml` is now mainly provided as an example, we can delete it later.
