### ISSUE TITLE
Set up a development branch

### ISSUE THREAD

**Issue by PGijsbers** [openml/automlbenchmark#165]
We all love to do some quick developing on a master branch to push our fixes as soon as possible, but it's prone to mistakes :) I think the project is mature enough to guard the master branch a bit more by introducing a develop branch. Bonus points if we can do a minor integration test for each commit to master.

**Comment by sebhrusen** [comment]
more important than the Dev branch i think (i personally always work on separate branch) is a more robust versioning policy, as it is very rudimentary currently (I tag the `master` branch once in a while, and this is when errors are made available...): `master` could remain the dev branch, but tagged branches should be robust, and users should be encouraged to use the `stable`  branch (the one used by default on aws).

**Comment by PGijsbers** [comment]
Maybe this is just some Github thing, but I don't see any `stable`  branch? Does `https://github.com/openml/automlbenchmark#stable` just use the latest tagged version?
But no matter the name, whether it's `develop/master`  or `master/stable`, a separate branch would be needed to push targeted critical bug fixes? Only using tags wouldn't allow for this. Especially important since we don't have comprehensive test coverage.

**Comment by sebhrusen** [comment]
`stable` is a tag, not a branch:  https://github.com/openml/automlbenchmark/tags
it usually points to the latest version tag, e.g. `v1.6`.

I see your point for critical bug fixes. In this case, I would create a `stable` branch then for compatibility with the existing logic: AWS will still be using `stable`, and we keep `master` for latest development as it is usually the case.

**Comment by PGijsbers** [comment]
The branch for the latest version remains `master`. For the latest stable release, the `stable` branch is now used.
