### ISSUE TITLE
Decouple resources from tasks in the benchmark

### ISSUE THREAD

**Issue by PGijsbers** [openml/automlbenchmark#17]
I think coupling the resources and tasks into a single file is not optimal.
This leads to a lot of duplicate benchmarks where only the resources specifications differ (see our current resources/benchmarks folder).
At the very least I think we should have separate files specifying resources and collections of tasks.
Perhaps we should only have files specifying the resources (if at all, since that would be easy to do from the command line too), and use [OpenML Studies](https://docs.openml.org/#studies-under-construction) to specify tasks.

The upsides would be:
 - easier to add a dataset: modify only one file if not using OpenML study, or none if we are.
 - rerunning a set of tasks with different resources would not require a new file.

Downsides:
 - no automatic public history of tasks added (if through an OpenML study).
 - not possibly to add arbitrary evaluation metrics (not possible in the current setup either, but would be easier to add as it would not rely on an OpenML implementation for it). I wouldn't be sure how to, if ever, allow arbitrary evaluation metrics on OpenML (as you would need to be able to run them in any of the supported languages).

@joaquinvanschoren are there any plans for something like versions for studies? That could negate one of the downsides.

**Comment by seb-h2o** [comment]
Closing this issue, created https://github.com/openml/automlbenchmark/issues/61 for the OpenML studies part.
