### ISSUE TITLE
ML-PLAN fails on some tasks

### ISSUE THREAD

**Issue by dev-rinchin** [openml/automlbenchmark#179]
Hi! 
I've tried to run ML-PLAN on task "Fashion-MNIST" in docker mode like this:
python3 runbenchmark.py MLPLAN openml/t/146825 -m docker
and it falls: [runbenchmark_20201022T123506_full.log](https://github.com/openml/automlbenchmark/files/5461619/runbenchmark_20201022T123506_full.log)
@mwever can you help me?
Thank you!

**Comment by mwever** [comment]
I will have a look at it

**Comment by mwever** [comment]
@sebhrusen Were there any changes concerning how the docker images are tagged? I just checked out a fresh version of the masterbranch and docker seems to have problems with creating docker images whenever there are capitals in the image name. A few month ago the image names have been completely in lower case, though.

**Comment by PGijsbers** [comment]
That's on me 😓 sorry. I'll fix that

**Comment by dev-rinchin** [comment]
@mwever why does this limitation affect my case? Image names no contain uppercase letters now:
![Screenshot 2020-10-30 at 16 44 59](https://user-images.githubusercontent.com/57899558/97712320-54e86180-1acf-11eb-876a-64fcd9b2bc7e.png)

**Comment by mwever** [comment]
This does not directly affect your case. I am just trying to reproduce your issue.

I had a lookt at your .log-file, and this indicates some awkward behavior since first ML-Plan starts off as expected but the lines containing only "Kill" as a log message look quite strangely. This is nothing coming from ML-Plan itself nor from the customized WEKA project ML-Plan uses as a backend. So I need to rerun this task as you have described it in your initial message. However, I currently cannot run it due to the failing docker build I outlined.

**Comment by PGijsbers** [comment]
@mwever sorry for the delay. The `ForceLowercaseImageNames` branch should fix the issue, but I am currently not able to verify this. Alternatively, you can overwrite the default image names by adding explicit names to the configuration file (`resources/frameworks.yaml`), e.g.:

```yaml
MLPlan:
  module: frameworks.MLPlan
  version: '0.2.3'
  project: http://mlplan.org
  image:
    image: mlplan
```

**Comment by mwever** [comment]
Thanks Pieter, I will check that!

**Comment by mwever** [comment]
Sorry for the long delay @dev-rinchin 

I ran the setup on my own and it appears to be a problem of the WEKA backend which does not adhere to the interrupts ML-Plan. We will try to track this issue down to make a new release of our interruptible WEKA adaptation and then of our ML-Plan CLI.

**Comment by mwever** [comment]
We have now released a new version of our ML-Plan CLI with several bug fixes and improvements. Can you please check, @dev-rinchin , whether the issue is now resolved?

**Comment by PGijsbers** [comment]
Running on today's `stable`, everything works for me (Windows host):
```
Summing up scores for current run:
                 id          task fold  framework constraint    result      metric  duration       seed
openml.org/t/146825 Fashion-MNIST    0 MLPlanWEKA       test -0.863872 neg_logloss     664.6 1264839298
openml.org/t/146825 Fashion-MNIST    1 MLPlanWEKA       test -1.522330 neg_logloss     626.1 1264839299
Job `docker.openml_t_146825.test.all_tasks.all_folds.MLPlanWEKA` executed in 1721.980 seconds.
``` 

Considering the issue is stale otherwise too, I will close this issue. Please re-open if you still experience issues.
