### ISSUE TITLE
Data security

### ISSUE THREAD

**Issue by hcvazquez** [openml/automlbenchmark#184]
Hi!

I plan to use the frameworks with my own datasets. My question is if I can be sharing data without knowing. 

When I use the framework, will there be data that is uploaded to the cloud or shared with openml website?

Thank you!

**Comment by sebhrusen** [comment]
Hi @hcvazquez, 

The app was originally only supporting OpenML datasets (those are public), but it is now possible to also use it against private datasets: see https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#file-datasets

Now, depending on how which mode you're rusing to run the benchmarks, here is what the app does with your data:
- local mode (default): the dataset is downloaded locally if necessary, and all the data remain on the local instance: nothing is uploaded, and no data or result are shared with anyone.
- docker/singularity mode: the container is started on the local system, so regarding data, it behaves exactly like the local mode.
- aws mode: the app runs on a secured EC2 instance that is by default terminated on completion. This EC2 instance will run the benchmark in "local" mode, so it will either need download the data if it's available through a public URL provided in the dataset definition (see link above), or the dataset can also theoretically be uploaded to a secured S3 and then downloaded automatically to EC2.

In any case, no data is automatically shared with 3rd parties (including OpenML), outside what is on S3 and temporary EC2 instances.

Note that we're planning to provide an option to automatically upload results to OpenML, but this well be (1) optional, (2) available only when benchmarking OpenML datasets.

If you have any additional question, especially maybe regarding the flow of data in AWS mode, feel free to ask.

**Comment by hcvazquez** [comment]
Awesome! That is a very clear answer. Thanks @sebhrusen!
