### ISSUE TITLE
Problem with sparse ARFF format

### ISSUE THREAD

**Issue by pplonski** [openml/automlbenchmark#197]
I have a problem running regression tasks with sparse ARFF format from suite 269. I'm trying to run an experiment in docker:

```
python3 runbenchmark.py mljarsupervised openml/t/13854 -m docker -f 0
```

Is it something on my side? Can it be because of the old openml version (0.10.2)?

**Comment by sebhrusen** [comment]
without any additional details, it's either a problem on your side or it's a duplicate of https://github.com/openml/automlbenchmark/issues/186

We currently don't really support sparse data, but if the converted data (to dense format) are not excessively large, it usually works, it's just suboptimal.

If you just want to test the dataset on the app, I recommend to try with the `constantpredictor_enc` framework:
```
python3 runbenchmark.py constantpredictor_enc openml/t/13854 -m docker -f 0
```

**Comment by pplonski** [comment]
Thank you! You were right. I found the reason. The target values in `exec.py` were `object` type. Casting to `float` solves the issue. Maybe there is some problem with the types during sending data in `numpy` vs `pandas` from `__init__.py` to `exec.py`? Not sure.
