### ISSUE TITLE
Docker image can't be build

### ISSUE THREAD

**Issue by Stefanenrichard** [openml/automlbenchmark#20]
Hi there, 

Thank you for your contribution to AutoML benchmarking, it is really good that there is a univeral standandard now. I just cloned the git repository and tried to run a benchmark using the 'docker' mode. I get the following error:

`
ERROR:
Docker image can't be built as current branch is not tagged as required `stable`. Please switch to the expected tagged branch first.`

I'm using the v1.0 branch. Could you please mark this one stable?

**Comment by seb-h2o** [comment]
@Stefanenrichard First, thanks for trying out the app: don't hesitate to provide any feedback. 

There is currently a few constraints when building the docker image:
- user must be on branch tagged as `stable`.
- there Git index and work tree should be empty (ie. no local changes).
This may be too restrictive but this was designed to ensure that docker images for various supported frameworks were all built using the same image without non-tested local changes.
However, there's a workaround to build a local image with your own changes (need to add this to doc, or think at a better way to avoid this restriction, maybe even remove it completely):
Just use the `-Xdocker.force_branch=False` parameter:
`python runbenchmark.py {framework} {benchmark} -m docker -Xdocker.force_branch=False`

**Comment by seb-h2o** [comment]
Also tagging `1.0` as`stable`

**Comment by Stefanenrichard** [comment]
Hi @seb-h2o, 

Thanks for the quick reply! I am working on my Master's thesis on AutoML, benchmarking is one of my research questions. I'm really glad you prepared this suite to speed op the process! So I hope to provide you with some proper feedback over the coming week(s). 

Currently, the force_branch parameter addition delivers me with the following issue:
(venv) C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark>python runbenchmark.py tpot -m docker -Xdocker.force_branch=False
Running `tpot` on `test` benchmarks in `docker` mode.
Loading frameworks definitions from C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\resources\frameworks.yaml.
Loading benchmark definitions from C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\resources\benchmarks\test.yaml.
Running cmd `docker images -q automlbenchmark/tpot:0.9.6-stable`
Building docker image automlbenchmark/tpot:0.9.6-stable.
Running cmd `docker build  -t automlbenchmark/tpot:0.9.6-stable -f C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\frameworks\TPOT\Dockerfile .`
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

Command 'docker build  -t automlbenchmark/tpot:0.9.6-stable -f C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\frameworks\TPOT\Dockerfile .' returned non-zero exit status 1.
Traceback (most recent call last):
  File "runbenchmark.py", line 113, in <module>
    bench.setup(automl.Benchmark.SetupMode[args.setup])
  File "C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\automl\docker.py", line 61, in setup
    self._build_docker_image(cache=(mode != Benchmark.SetupMode.force))
  File "C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\automl\docker.py", line 161, in _build_docker_image
    script=self._docker_script
  File "C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\automl\utils.py", line 657, in run_cmd
    raise e
  File "C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\automl\utils.py", line 644, in run_cmd
    universal_newlines=True)
  File "C:\Users\riooms\AppData\Local\Continuum\anaconda3\Lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'docker build  -t automlbenchmark/tpot:0.9.6-stable -f C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\frameworks\TPOT\Dockerfile .' returned non-zero exit status 1.

**Comment by seb-h2o** [comment]
@Stefanenrichard I'm sorry but the Windows support is very very limited today.
You should be able to run public images: https://hub.docker.com/u/automlbenchmark.
These are the images that were used to produce the paper's results:https://openml.github.io/automlbenchmark/results.html.
 
But if you plan building fresh images locally, I don't think it's ever been tested on Windows: this is something we could invest some time in the future, but currently I'd recommend to use a Linux environment. macOS works as well with most frameworks (still issues with `autosklearn` though).

**Comment by seb-h2o** [comment]
> "docker build" requires exactly 1 argument
> Command 'docker build -t automlbenchmark/tpot:0.9.6-stable -f C:\Users\riooms\OneDrive - Deloitte (O365D)\Thesis\Benchmark\automlbenchmark\frameworks\TPOT\Dockerfile .' returned non-zero exit status 1.

This is probably due the spaces in your path, but can't guarantee this will work without.

**Comment by seb-h2o** [comment]
Also the fact that it's building the image `docker build -t automlbenchmark/tpot:0.9.6-stable`, instead of downloading it, is interesting. This is definitely a problem as the image is publicly available.

**Comment by seb-h2o** [comment]
> Also the fact that it's building the image docker build -t automlbenchmark/tpot:0.9.6-stable, instead of downloading it, is interesting.

That's a bug on our side, we don't do automatic pull images on local runs: will fix this.

**Comment by Stefanenrichard** [comment]
> 
> 
> Also the fact that it's building the image `docker build -t automlbenchmark/tpot:0.9.6-stable`, instead of downloading it, is interesting. This is definitely a problem as the image is publicly available.
> 
> Can you try to pull it manually first?
> `docker pull automlbenchmark/tpot:0.9.6-stable`?

I have done this, seemed to remove the problem, as well as the removal of spaces as you mentioned above. Due to the lack of windows support I will move on to running on AWS, thanks again for your help!

**Comment by seb-h2o** [comment]
@Stefanenrichard : the lack of Windows support is for building and running locally: you should be able to run app in docker mode anywhere though.

**Comment by Stefanenrichard** [comment]
@seb-h2o I have some settings on my laptop that prevent Docker from communicating with C:, so that will be hard. Thanks again for your help. If there is something that I will run into on AWS, I'll let you know in another threat to keep everything well-organized.
