### ISSUE TITLE
Class probabilities order in multiclass predictions

### ISSUE THREAD

**Issue by pplonski** [openml/automlbenchmark#212]
In the multiclass classification dataset Helena (task id = 359984) the classes are as object type:

```
array(['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18',
        '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28',
        '29', '3', '30', '31', '32', '33', '34', '35', '36', '37', '38',
        '39', '4', '40', '41', '42', '43', '44', '45', '46', '47', '48',
        '49', '5', '50', '51', '52', '53', '54', '55', '56', '57', '58',
        '59', '6', '60', '61', '62', '63', '64', '65', '66', '67', '68',
        '69', '7', '70', '71', '72', '73', '74', '75', '76', '77', '78',
        '79', '8', '80', '81', '82', '83', '84', '85', '86', '87', '88',
        '89', '9', '90', '91', '92', '93', '94', '95', '96', '97', '98',
        '99'], dtype=object)
```

with so many classes, the order of probabilities columns in predictions matter.  If the predictions column will be not in the same order as applied to the target column in the scoring metric, then the result will be completely wrong. But the ML model will be correct.

Is there any way to check if prediction columns with probabilities are in the correct order (the same order that will be applied to the target column in the scoring metric)? This problem only occurs only for multiclass problems with classes > 10.

**Comment by pplonski** [comment]
Looks like I'm missing `probabilities_labels`. Closing the issue as it depends on the framework `exec.py` code.

**Comment by sebhrusen** [comment]
@pplonski, correct if you're including `probabilities_labels` in the returned results, it will automatically reorder the predictions columns if needed.
