### ISSUE TITLE
Add option to error out if resource constraints can not be met

### ISSUE THREAD

**Issue by PGijsbers** [openml/automlbenchmark#214]
The current behavior if the constraint specifies more memory (and cores?) than available on the machine is to log it as a warning. I think it would be useful to have an option which can be turned on which instead stops execution if such violations are identified. Using this option would avoid a scenario where the warning is missed and experiments are run with different resources than expected.

**Comment by sebhrusen** [comment]
@PGijsbers we need to review together the resource constraints logic (esp. memory reserved for the OS, disk space and so on), I'm not really happy with this today: they're not  clear.

**Comment by PGijsbers** [comment]
Added in #288
