### ISSUE TITLE
autosklearn error in smac

### ISSUE THREAD

**Issue by flokde** [openml/automlbenchmark#215]
Hi Seb and Team,

I am having trouble running a benchmark on autosklearn. In a freshly cloned respository of the automlbenchmark I am getting an error when running `python3 runbenchmark.py autosklearn test` in each autosklearn run:

`ModuleNotFoundError: No module named 'smac.tae.execute_ta_run'`

Is that a problem on my side or was smac maybe updated?
I am running the benchmark on CentOS 7 with python 3.7.9.

Thanks so much and all the best!

**Comment by sebhrusen** [comment]
Hi @flokde! yes, this is an issue with requirements constraints on that version of `autosklearn`: `smac` released a backwards incompatible version, and autosklearn requirements were not strict enough.

You can try to declare your own framework definition and change the version number to something more recent... although it's probably not necessary as autosklearn latest version will be available in `master` soon:
 https://github.com/openml/automlbenchmark/pull/183

Please also note that for future 2.0 release, benchmarks will probably run the last framework release version by default and users will have to have their own custom definition if they need a specific version: see https://github.com/openml/automlbenchmark/pull/196
and https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#framework-definition for local custom definitions.
