### ISSUE TITLE
Updating AutoGluon framework to v0.1.x

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#232]
AutoGluon v0.1.x is an API breaking change to the existing v0.0.x version in automlbenchmark. While I have gotten v0.1.x to work on my local branch, versions <0.1 will no longer work due to the framework code differing.

What is the recommended approach in this case? Do we want to keep the v0.0.x functionality via some `AutoGluonLegacy` or `AutoGluon_v0_0_x` framework?

**Comment by Innixma** [comment]
Planning to send PR in 1-2 days to update AG framework (ideally to be used in the upcoming automlbenchmark run)

**Comment by PGijsbers** [comment]
Auto-sklearn currently supports multiple versions from the same script ([here](https://github.com/openml/automlbenchmark/blob/f49ddfa2583643173296ed8ab45a8c14c62a6987/frameworks/autosklearn/exec.py#L86)). That should be simple enough and makes it easier for the user (it doesn't become "a different framework").

We still have to find a good balance between having backwards compatibility (old versions of the automl system on new version of the framework) and the burden we put on the people writing the integration code. But we would greatly appreciate if we could side-step that for now.

**Comment by Innixma** [comment]
Opened #237 for the integration PR. I haven't added support for old versions `<=0.0.15` in it yet as it needs a bit of effort (imports are not the same so have to have some kind of try/except logic for the imports)
