### ISSUE TITLE
Datasets from locations other than OpenML

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#241]
Currently, automlbenchmark is an excellent way to benchmark on openml datasets, but I was wondering if there is support / plans for formats outside of openml, such as datasets in S3 or local disk.

I'd assume these datasets can have the same functionality so long as they have metadata files that dictate the split indices / dataset name / dtypes / etc.

Any plans for this kind of functionality?

**Comment by PGijsbers** [comment]
[Local and remote datasets](https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#file-datasets) are already supported, let us know if you encounter issues. 
As for downloading from other sources and/or supporting other formats, we are open to PRs but don't have plans to add this ourselves anytime soon.

**Comment by Innixma** [comment]
Awesome, this answers my question! I'll give custom datasets from S3 a try and see how it goes.
