### ISSUE TITLE
Schedule for the 2021 benchmark

### ISSUE THREAD

**Issue by dev-rinchin** [openml/automlbenchmark#264]
Hi! 
Do you have a schedule for the 2021 benchmark run? When are you planing to get the results?

**Comment by dev-rinchin** [comment]
Where can I find a list of fixed framework versions for the 2021 benchmark?
@PGijsbers I found the list here:
https://github.com/openml/automlbenchmark/blob/fw_2020q1/resources/frameworks_2021Q1.yaml
Do you plan to add LightAutoML?

**Comment by PGijsbers** [comment]
Sorry. Yes, we are planning to add LightAutoML! I can't promise an exact timeline - things have not been going according to plan - but we are doing it as soon as possible. I'm still hopeful we can start experiments within a month.

**Comment by alexmryzhkov** [comment]
Hello @PGijsbers!

I would like to ask you how is it going with the benchmark? Are there any expectations about the moment it will be finished and the final results will be announced? 

Alex

**Comment by PGijsbers** [comment]
Sorry for the slow reply. We're looking to start next week (but won't immediately queue all jobs). I am still hopeful results will be available before the end of the month, but I've underestimated the amount of work before 😞.

**Comment by alexmryzhkov** [comment]
@PGijsbers Thanks for info, nice to hear. 104 datasets will take enormous resources power ;)

**Comment by dev-rinchin** [comment]
@PGijsbers hi! any updates?

**Comment by PGijsbers** [comment]
Unfortunately I wasn't able to work much on the benchmark recently, but we're almost there. I've been very poor with estimating work left, but at this point I think there is almost nothing that _needs_ to be done before we can start with a `stable` release. I'll run validation tests on the latest versions of all the frameworks next week and contact authors who released versions since last reporting in #235 (speaking of- can you confirm that we should fix LAMA to 0.2.15?). I think I'm done giving any estimates of when results are in, burnt myself enough on that in the past, but soon™.

**Comment by PGijsbers** [comment]
We just did a stable release, which is in principle the version we will use (we will only patch if required). We will now start preparing for the experiments by building new docker images and doing a few trials. Hopefully we can start on a large scale next week. I still expect it to take a few weeks before we have results as there is a significant number of compute hours involved. Unfortunately our AWS permissions are limited to fewer instances than we would like and spot instances seem rather unavailable lately, but we are doing our best.

**Comment by dev-rinchin** [comment]
Hi @PGijsbers! have you finished the experiment? Where I can found the results for the experiments?
Also I want to update the lightautoml version in automlbenchmark, where do I need to update the file? In frameworks_2021Q3.yaml or in next future yaml file?

**Comment by PGijsbers** [comment]
Hi, sorry for the delay once more! We are currently running the experiments. We will share the results and our paper (as preprint on arxiv) when we do our submission (current schedule is January).

**Comment by dev-rinchin** [comment]
@PGijsbers could you please provide the versions used in this experiment for each framework? Are they listed in frameworks_2021Q3.yaml?

**Comment by PGijsbers** [comment]
Yes, specifically on the `stable-v2` branch ([file](https://github.com/openml/automlbenchmark/blob/stable-v2/resources/frameworks_2021Q3.yaml)). Roughly speaking, these are the versions that were available three months ago for each framework.

**Comment by alexmryzhkov** [comment]
> Hi, sorry for the delay once more! We are currently running the experiments. We will share the results and our paper (as preprint on arxiv) when we do our submission (current schedule is January).

Hi @PGijsbers,

how is it going with the benchmark? Is the pre-print already published? We are still waiting for the results from your side to cite them in our publications :)

Alex

**Comment by PGijsbers** [comment]
Still on schedule for late January/early February. Don't worry, I'll post back here when we make publish the results/preprint :)

**Comment by alexmryzhkov** [comment]
@PGijsbers any updates? We are currently working on our publication with the deadline by the end of this week

**Comment by PGijsbers** [comment]
@alexmryzhkov We should have a preprint available sometime around February 19th (which I realize is not in time). Is it just for citation purposes? And is there a round of reviews still, or is this a camera-ready candidate? If yes to both, perhaps it would be possible to update the citation after review (you could add a reference with "to be published" or even the workshop paper)?
If not, do you mind sending me a quick [e-mail](https://research.tue.nl/en/persons/pieter-gijsbers) with exactly what you need? Then I can discuss with the team if we can help and how to handle that.

**Comment by alexmryzhkov** [comment]
@PGijsbers the email is in your inbox :)

**Comment by PGijsbers** [comment]
Hi everyone, we updated our timeline. We want to take a little bit more time to make sure the paper is in the best shape it can be. This means that we moved up our deadline by about one month. We will also get in touch with the authors of the evaluated frameworks before releasing the preprint for a chance to comment. More details will follow by mail when we're ready.

**Comment by PGijsbers** [comment]
Closing this issue since the preprint is now available: https://arxiv.org/abs/2207.12560
We do plan to do additional experiments this fall, but will get in touch separately (not as a continuation of this issue).
