### ISSUE TITLE
Auto-WEKA integration broken

### ISSUE THREAD

**Issue by mfeurer** [openml/automlbenchmark#331]
Hi together,

I think the Auto-WEKA integration, more specifically, the installation, is broken. While building the container, I get:
```
#19 66.69 --2021-06-28 13:27:15--  http://www.cs.ubc.ca/labs/beta/Projects/autoweka/autoweka-stable.zip
#19 66.69 Resolving www.cs.ubc.ca (www.cs.ubc.ca)... 142.103.6.5
#19 66.96 Connecting to www.cs.ubc.ca (www.cs.ubc.ca)|142.103.6.5|:80... connected.
#19 67.16 HTTP request sent, awaiting response... 404 Not Found
#19 67.16 2021-06-28 13:27:15 ERROR 404: Not Found.
#19 67.17 
#19 67.17 unzip:  cannot find or open /bench/frameworks/AutoWEKA/lib/autoweka-stable.zip, /bench/frameworks/AutoWEKA/lib/autoweka-stable.zip.zip or /bench/frameworks/AutoWEKA/lib/autoweka-stable.zip.ZIP.
#19 67.17 find: ‘/bench/frameworks/AutoWEKA/lib/autoweka*.zip’: No such file or directory
#19 67.17 
#19 67.17 
#19 67.17 
#19 67.17 --2021-06-28 13:27:15--  http://www.cs.ubc.ca/labs/beta/Projects/autoweka/autoweka-stable.zip
#19 67.17 Resolving www.cs.ubc.ca (www.cs.ubc.ca)... 142.103.6.5
#19 67.17 Connecting to www.cs.ubc.ca (www.cs.ubc.ca)|142.103.6.5|:80... connected.
#19 67.17 HTTP request sent, awaiting response... 404 Not Found
#19 67.17 2021-06-28 13:27:15 ERROR 404: Not Found.
#19 67.17 
#19 67.17 unzip:  cannot find or open /bench/frameworks/AutoWEKA/lib/autoweka-stable.zip, /bench/frameworks/AutoWEKA/lib/autoweka-stable.zip.zip or /bench/frameworks/AutoWEKA/lib/autoweka-stable.zip.ZIP.
#19 67.17 find: ‘/bench/frameworks/AutoWEKA/lib/autoweka*.zip’: No such file or directory
#19 67.17 
#19 67.18 Setup of framework AutoWEKA completed successfully.
#19 DONE 67.7s
```
which suggests that the expected file holding Auto-WEKA is not available. However, this does not trigger the container build to stop.

The Q2 framework setup instead uses version 2.6 instead which indeed works for me. Would it make sense to change the installation script to use the latest known version in case the user wants to run version `stable`?

**Comment by PGijsbers** [comment]
I opened an [issue](https://github.com/automl/autoweka/issues/94) at the AutoWEKA repository, considering the project officially doesn't plan any updates. The best solution would be to have a permalink that points to the latest AutoWEKA version (and resolve "stable" to that link in `setup.sh`. But I would like to wait until clarification from the authors before making a decision on how we handle this.

**Comment by PGijsbers** [comment]
There's now a permanent url for fetching the latest version of Auto-WEKA (see the linked issue). We should resolve "stable" to that.
