### ISSUE TITLE
Why does the benchmark use its own OpenML cache directory by default?

### ISSUE THREAD

**Issue by mfeurer** [openml/automlbenchmark#332]
Hey, I was wondering why the benchmark does not use the standard OpenML-Python cache directory by default, but rather [uses a custom one](https://github.com/openml/automlbenchmark/blob/master/runbenchmark.py#L17) which defaults to an old location of the OpenML-Python cache directory?

It might be a good idea to update this location as it might be not obvious for a user that the benchmark tries to download the files from OpenML itself.

**Comment by PGijsbers** [comment]
See #321. It's not ideal, but for now we want to keep a single input folder, and using the existing openml cache would mean we would add files to that directory which might not be expected by `openml-python`.

**Comment by mfeurer** [comment]
Thanks a lot.
