### ISSUE TITLE
Old Pandas ver in requirements.txt

### ISSUE THREAD

**Issue by drheavy** [openml/automlbenchmark#344]
In requirements.txt there is a Pandas version 1.2.4, but with this version I get an error on each test ("AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '.../projects/automlbenchmark/venv/lib/python3.8/site-packages/pandas/core/internals/blocks.py")
After Pandas updating to the last version 1.3.0 it works well. I think requirements.txt should be updated.

**Comment by PGijsbers** [comment]
Per the discussion in #339 we're planning to bypass this problem altogether by avoiding working with pickled dataframes and instead prefer to use parquet.

**Comment by PGijsbers** [comment]
I'm leaving this issue open to acknowledge there currently is an issue with the pandas version incompatibility.

**Comment by PGijsbers** [comment]
There should no longer be a need to upgrade pandas since we no longer use pickle as the default serialization format (#345).
