### ISSUE TITLE
Decision tree not possible with docker on aws

### ISSUE THREAD

**Issue by richooms** [openml/automlbenchmark#35]
Hi there,

This is probably not a usecase that you have tried (or want to support) when trying to run a decision tree with docker enabled this gave an error (see attached logs). I ran it without docker on aws and its working just fine. This is just a heads-up, no actual problem for me :)

[runbenchmark_20190701T201906.log](https://github.com/openml/automlbenchmark/files/3347249/runbenchmark_20190701T201906.log)

**Comment by seb-h2o** [comment]
Hi @richooms , you're right, we don't really want to support it: DecisionTree is basically a toy-framework, and we didn't build/upload any docker image for it.
Thanks for heads-up!
