### ISSUE TITLE
How to parallel running this experiment on my local server?

### ISSUE THREAD

**Issue by zhenlingcn** [openml/automlbenchmark#354]
I have a single server with 96 cores, and I don't want to build a new docker image because my algorithm package relies on a lot of dependencies. As a result, I hope I can run it on my local server. Is it possible for me to do that?

**Comment by zhenlingcn** [comment]
By the way, I find that the commented out code fragments with respect to parallelization in the local model creates multiple threads rather than processes for parallelization. However, in Python, a correct implementation of real parallelization should be multi-processing. Consequently, is there any quick way to solve that issue? I just changed the creation of thread to the creation of process, but it doesn't work.

**Comment by sebhrusen** [comment]
> However, in Python, a correct implementation of real parallelization should be multi-process

That's not correct, it depends what the threads or processes are doing.
If the parallelized task is CPU intensive, then you should use processes, otherwise it's easier and absolutely safe to use threads.
In amlb, the frameworks run in a sub-process, we use multi-threads for for parallelization — especially in AWS mode — because those threads just communicate with EC2 servers, there is absolutely no reason to create subprocesses that will just to do async http requests...

**Comment by sebhrusen** [comment]
> I have a single server with 96 cores, and I don't want to build a new docker image because my algorithm package relies on a lot of dependencies. As a result, I hope I can run it on my local server. Is it possible for me to do that?

I'll need more details here. You integrated your package in the `frameworks`?
If so, local execution is the default behaviour:
```bash
> python runbenchmark.py your_framework
```
will run locally, without docker image.
You need — or it automatically creates a docker image — only if running
```bash
> python runbenchmark.py your_framework -m docker
```

**Comment by zhenlingcn** [comment]
Okay, thanks for your help. However, I want to fully leverage all my cores, and the GIL of python will impede me doing that. A possible solution might be relying on the docker. However, I don't want to run the container because I don't want to reconfigure my development environment. As a result, I modified some codes to let all tasks submit to a process pool, and let that pool control the execution of all tasks. This seems to work well.
```python
def worker(job):
    return job.start()

class ExecutorJobRunner(JobRunner):

    def __init__(self, pool_executor_class, jobs, parallel_jobs):
        super().__init__(jobs)
        self.pool_executor_class = pool_executor_class
        self.parallel_jobs = parallel_jobs

    def _run(self):
        pool = ProcessPool(self.parallel_jobs)
        self.results.extend(pool.map(worker, self.jobs))
        clean_priority_queue(self._queue)
        pool.close()

def clean_priority_queue(q):
    while not q.empty():
        try:
            q.get(False)
        except queue.Empty:
            continue
        q.task_done()
```
