### ISSUE TITLE
Turn off telemetry of MLNet 

### ISSUE THREAD

**Issue by PGijsbers** [openml/automlbenchmark#356]
By default MLNet has telemetry enabled ([source](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/ml-net-cli-telemetry#opt-out-of-data-collection)). We want this to be opt-in rather than opt-out for the benchmark, especially since we don't expect all users to extensively read the documentation for each framework.

**Comment by mcnojo** [comment]
I've added the necessary line to opt out by setting the env variable and it runs against the MLNet tests without issue, but is there any desire to add a toggle to the CLI for opting back in?  If so, how should I proceed with this/what resources can give me a better sense of the code?  I've been reading the AutoML functions for a few hours without much progress.

**Comment by PGijsbers** [comment]
Where do you set the environment variable? Through python in `exec.py`? If so, then using a script parameter would be best. These can be set through the [configuration](https://github.com/openml/automlbenchmark/blob/b90cd9b30ff9c9048ae3240ecdece55a0a3da189/resources/frameworks.yaml#L28), and from the `exec.py` are provided through [config.framework_params](https://github.com/openml/automlbenchmark/blob/b90cd9b30ff9c9048ae3240ecdece55a0a3da189/frameworks/AutoGluon/exec.py#L122). This is hidden in the very last [info](https://openml.github.io/automlbenchmark/docs/extending/framework/) block on the framework page - we should make it more visible, and in the future separate out framework parameters from script parameters :)
So, in that case you can make setting the environment variable conditional on the presence of a parameter in the framework configuration. These are still not exposed to the CLI (though invoking the definition which has telemetry ON is available through the CLI, of course).

**Comment by mcnojo** [comment]
Very helpful context, thank you!  The environment variable was originally set in exec.py.

After reading the above, I've changed this to set a framework parameter so that exec.py will pull from the config and set the environment variable conditionally.  

I've opened a pull request [here](https://github.com/openml/automlbenchmark/pull/619#issue-2259391697).

**Comment by PGijsbers** [comment]
Closed by #619
