### ISSUE TITLE
Flaml does not support tag 'stable' or 'latest'

### ISSUE THREAD

**Issue by eddiebergman** [openml/automlbenchmark#408]
Hi,

Do you plan to support these tags for flaml? If not, is there a particular reason?

---
While setting up some infrastructure for automating bench marking, I noticed the following two commands fail:
```bash
python runbenchmark.py flaml:stable
python runbenchmark.py flaml:latest
```

Turns out flaml is not included in `resources/frameworks_{stable,latest}.yaml`.

**Comment by PGijsbers** [comment]
There is no reason that they are not added as far as I am aware, and I see no issue with adding them now (as far as I can tell it's even already supported in [their setup script](https://github.com/openml/automlbenchmark/blob/master/frameworks/flaml/setup.sh)).
