### ISSUE TITLE
Add support for AILib (aka. ML-Plan)

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#43]
New OS framework to be added:
https://github.com/fmohr/AILibs

looking for contributors.

**Comment by mwever** [comment]
Hi,

I now integrated ML-Plan with the AutoML Benchmark. More specifically, I added two default frameworks for ML-Plan:

- **MLPlanWEKA**: ML-Plan using WEKA as a basis for configuring ML algorithms. It is capable of tackling classification as well as regression tasks. However, we did not benchmark it yet for regression. For internal validation, MLPlanWEKA offers acc, auc, logloss, and f1 for classification, and rmse, mse, mae, rmsle, and r2 for regression.
- **MLPlanSKLearn**: ML-Plan using scikit-learn as a basis for configuring ML algorithms. It is also capable of dealing with classification and regression tasks. Metrics are the same for classification and regression as for MLPlanWEKA.

I have only one question left: How is the value of the positive class provided for AUC and F1 in case of binary classification?
