### ISSUE TITLE
[BUG] Numerous dataset errors

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#457]
Related Issue: #456 

Sometime around March 7th, something changed in AutoMLBenchmark runs that caused many datasets to begin failing on all frameworks. This issue is currently highly disruptive for me as I am trying to get benchmark results for a paper and am unable to get past this error. I can confirm that AutoMLBenchmark was working correctly on March 3rd.

From my own investigation it appears that the scoring logic in AutoMLBenchmark has a bug that is not using the label column for y_true but instead some other column in features. However, it is very hard to debug the code so I haven't been able to identify why this is happening, but can confirm that the output predictions coming from AutoGluon are correct and should not result in an error. This issue seems to be related to something on the data hosting side that changed in early March.

Code example:

```
# Setup
python3 -m venv ./venv
source venv/bin/activate
git clone https://github.com/openml/automlbenchmark.git --branch master --depth 1
cd automlbenchmark
python -m pip install -r requirements.txt
```

```
# Run constantpredictor on Sylvine
python runbenchmark.py constantpredictor openml/t/359972 test

Out:
                 id    task fold         framework constraint metric  duration       seed                                                      info
openml.org/t/359972 sylvine    0 constantpredictor       test    auc       0.2 1796721180 ValueError: 2 columns passed, passed data had 155 columns
openml.org/t/359972 sylvine    1 constantpredictor       test    auc       0.0 1796721181 ValueError: 2 columns passed, passed data had 153 columns

# Run RandomForest on Sylvine
python runbenchmark.py RandomForest openml/t/359972 test

Out:
                 id    task fold    framework constraint metric  duration      seed                                                      info
openml.org/t/359972 sylvine    0 RandomForest       test    auc      43.3 199012137 ValueError: 2 columns passed, passed data had 155 columns
openml.org/t/359972 sylvine    1 RandomForest       test    auc      44.2 199012138 ValueError: 2 columns passed, passed data had 153 columns

# Run AutoGluon on Sylvine
python runbenchmark.py autogluon openml/t/359972 test

Out:
                 id    task fold framework constraint metric  duration      seed                                                    info
openml.org/t/359972 sylvine    0 AutoGluon       test    auc      25.4 859375978 ResultError: y contains previously unseen labels: '203'
openml.org/t/359972 sylvine    1 AutoGluon       test    auc      26.7 859375979 ResultError: y contains previously unseen labels: '243'

```

This issue occurs on at minimum the following datasets:

```
id			task
openml.org/t/189356	albert
openml.org/t/190412	arcene
openml.org/t/359973	christine
openml.org/t/168909	dilbert
openml.org/t/189355	dionis
openml.org/t/168910	fabert
openml.org/t/189922	gina
openml.org/t/359988	guillermo
openml.org/t/359984	helena
openml.org/t/211979	jannis
openml.org/t/359991	kick
openml.org/t/190392	madeline
openml.org/t/233215	Mercedes_Benz_Greener_Manufacturing
openml.org/t/359990	MiniBooNE
openml.org/t/359947	MIP-2016-regression
openml.org/t/190410	philippine
openml.org/t/359989	riccardo
openml.org/t/359986	robert
openml.org/t/359972	sylvine
openml.org/t/359985	volkert
```

When running AutoGluon, these are the errors I get for them:

```
ResultError: y contains previously unseen labels: '1.0'
ResultError: y contains previously unseen labels: '28'
ResultError: y contains previously unseen labels: '208.0'
ResultError: y contains previously unseen labels: '0.0449564'
ResultError: y contains previously unseen labels: '7504.0'
ResultError: y contains previously unseen labels: '0.0'
ResultError: y contains previously unseen labels: '79'
ResultError: y contains previously unseen labels: '0.0'
ResultError: y contains previously unseen labels: '0.0490914'
ResultError: y contains previously unseen labels: '0.037147'
ResultError: y contains previously unseen labels: '1250640000.0'
ResultError: y contains previously unseen labels: '548.0'
ResultError: could not convert string to float: 'a'
ResultError: y contains previously unseen labels: '5.5562'
ResultError: could not convert string to float: 'timeout'
ResultError: y contains previously unseen labels: '1.90305'
ResultError: y contains previously unseen labels: '0.13852'
ResultError: y contains previously unseen labels: '308.0'
ResultError: y contains previously unseen labels: '203'
ResultError: y contains previously unseen labels: '0.13397'
```

I can confirm that the install versions (pip freeze + python version) have been unchanged since at least January 2022, so it is not a dependency issue in the code.

Python 3.7.7
pip freeze:
<details>

boto3==1.17.74
botocore==1.20.74
certifi==2020.12.5
chardet==4.0.0
idna==2.10
jmespath==0.10.0
joblib==1.0.1
liac-arff==2.5.0
minio==7.0.3
numexpr==2.7.3
numpy==1.20.3
openml==0.12.2
pandas==1.2.4
psutil==5.8.0
pyarrow==4.0.0
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
ruamel.yaml==0.17.4
ruamel.yaml.clib==0.2.2
s3transfer==0.4.2
scikit-learn==0.24.2
scipy==1.6.3
six==1.16.0
tables==3.6.1
threadpoolctl==2.1.0
urllib3==1.26.4
xmltodict==0.12.0

</details>

**Comment by PGijsbers** [comment]
This _should_ be resolved for the datasets connected to the tasks in benchmarking suites 269 and 271 (the remainder of the datasets still need updating as we prioritized the suites). The `constantpredictor` successfully produced results on the first fold of each task of the benchmark.
You will need to clear your cache (see where it is located with `openml.config.cache_directory`), at least the erroneous datasets (in the `org/openml/www/datasets`  subdirectory).

**Comment by PGijsbers** [comment]
Closing this issue, leaving the other one open to fix on the indexing issue.
