### ISSUE TITLE
Why is stable-v2 ahead of master branch?

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#458]
"This branch is 27 commits ahead, 13 commits behind master."

stable-v2 includes nice improvements like https://github.com/openml/automlbenchmark/pull/433

Yet this is not present in master branch. Is there a plan to have master branch be up to date? Ideally I'd assume that master branch would always be ahead or equal to any stable branch.

**Comment by PGijsbers** [comment]
Patches in `stable-v2` will be merged into `master`. `stable-v2` is supposed to be frozen for consistency in the experiments we ran, but we required certain fixes to run our experiments.

**Comment by PGijsbers** [comment]
@sebhrusen I have no strong opinion on how to apply those patches back into `master`, but I've got a feeling you do :) would you be willing to take care of this?

**Comment by sebhrusen** [comment]
I started to work on https://github.com/openml/automlbenchmark/issues/416 a few weeks ago to fix the versioning workflow which currently prevents us from merging changes in `stable` branches back to `master` automatically.
I'll try to work back on this soon.
