### ISSUE TITLE
Subprocess running exec_run died abruptly

### ISSUE THREAD

**Issue by ajoeajoe** [openml/automlbenchmark#46]
**** Random Forest (sklearn) ****

Running RandomForest with a maximum time of 3600s on 2 cores.
We completely ignore the requirement to stay within the time limit.
We completely ignore the advice to optimize towards metric: auc.
CPU Utilization: 48.4%
Memory Usage: 9.9%
Disk Usage: 59.0%
CPU Utilization: 100.0%
Memory Usage: 20.7%
Disk Usage: 59.0%
CPU Utilization: 100.0%
Memory Usage: 30.8%
Disk Usage: 59.0%
CPU Utilization: 100.0%
Memory Usage: 42.5%
Disk Usage: 59.0%
CPU Utilization: 100.0%
Memory Usage: 45.9%
Disk Usage: 59.0%
CPU Utilization: 100.0%
Memory Usage: 91.3%
Disk Usage: 59.0%
Subprocess running exec_run died abruptly.
Traceback (most recent call last):
  File "/content/automls/automlbenchmark/automl/utils.py", line 698, in call_in_subprocess
    result = q.get_nowait()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 126, in get_nowait
    return self.get(False)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 107, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/automls/automlbenchmark/automl/benchmark.py", line 371, in run
    meta_result = framework.run(self._dataset, task_config)
  File "/content/automls/automlbenchmark/frameworks/RandomForest/__init__.py", line 10, in run
    return call_in_subprocess(exec_run, *args, **kwargs)
  File "/content/automls/automlbenchmark/automl/utils.py", line 704, in call_in_subprocess
    raise Exception("Subprocess running {} died abruptly.".format(target.__name__))
Exception: Subprocess running exec_run died abruptly.
Metric scores: { 'acc': nan,
  'auc': nan,
  'duration': nan,
  'fold': 0,
  'framework': 'RandomForest',
  'id': 'openml.org/t/189354',
  'info': 'Exception: Subprocess running exec_run died abruptly.',
  'mode': 'local',
  'models': nan,
  'params': "{'n_estimators': 2000}",
  'result': nan,
  'seed': 3104790822,
  'tag': 'stable',
  'task': 'Airlines',
  'utc': '2019-07-18T18:37:20',
  'version': '0.19.2'}
Job local_Airlines_0_RandomForest executed in 748.140 seconds.

-------------------------------------------
Starting job local_Airlines_1_RandomForest.
Assigning 2 cores (total=2) for new task Airlines.
Assigning 9945 MB (total=13023 MB) for new Airlines task.
Running task Airlines on framework RandomForest with config:
TaskConfig(framework='RandomForest', framework_params={'n_estimators': 2000}, type='classification', name='Airlines', fold=1, metrics=['auc', 'acc'], metric='auc', seed=3104790823, max_runtime_seconds=3600, cores=2, max_mem_size_mb=9945, min_vol_size_mb=-1, input_dir='/root/.openml/cache', output_dir='/content/automls/automlbenchmark/results/local_randomforest_openml_20190718T163809', output_predictions_file='/content/automls/automlbenchmark/results/local_randomforest_openml_20190718T163809/predictions/randomforest_Airlines_1.csv')

**** Random Forest (sklearn) ****

Running RandomForest with a maximum time of 3600s on 2 cores.
We completely ignore the requirement to stay within the time limit.
We completely ignore the advice to optimize towards metric: auc.
CPU Utilization: 80.5%
Memory Usage: 12.8%
Disk Usage: 59.1%
CPU Utilization: 99.9%
Memory Usage: 23.4%
Disk Usage: 59.1%
CPU Utilization: 100.0%
Memory Usage: 35.9%
Disk Usage: 59.1%
CPU Utilization: 100.0%
Memory Usage: 48.7%
Disk Usage: 59.1%
CPU Utilization: 100.0%
Memory Usage: 57.2%
Disk Usage: 59.1%
Subprocess running exec_run died abruptly.
Traceback (most recent call last):
  File "/content/automls/automlbenchmark/automl/utils.py", line 698, in call_in_subprocess
    result = q.get_nowait()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 126, in get_nowait
    return self.get(False)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 107, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/automls/automlbenchmark/automl/benchmark.py", line 371, in run
    meta_result = framework.run(self._dataset, task_config)
  File "/content/automls/automlbenchmark/frameworks/RandomForest/__init__.py", line 10, in run
    return call_in_subprocess(exec_run, *args, **kwargs)
  File "/content/automls/automlbenchmark/automl/utils.py", line 704, in call_in_subprocess
    raise Exception("Subprocess running {} died abruptly.".format(target.__name__))
Exception: Subprocess running exec_run died abruptly.
Metric scores: { 'acc': nan,
  'auc': nan,
  'duration': nan,
  'fold': 1,
  'framework': 'RandomForest',
  'id': 'openml.org/t/189354',
  'info': 'Exception: Subprocess running exec_run died abruptly.',
  'mode': 'local',
  'models': nan,
  'params': "{'n_estimators': 2000}",
  'result': nan,
  'seed': 3104790823,
  'tag': 'stable',
  'task': 'Airlines',
  'utc': '2019-07-18T18:47:53',
  'version': '0.19.2'}
Job local_Airlines_1_RandomForest executed in 632.856 seconds.

**Comment by PGijsbers** [comment]
Could you give the command line argument with which you started this job (e.g. local/aws)?

**Comment by ajoeajoe** [comment]
I put all the https://www.openml.org/s/218 dataset in one file name openml.yaml，and just try to run using "python3 runbenchmark.py RandomForest openml", I want to get the result as you give in paper https://www.automl.org/wp-content/uploads/2019/06/automlws2019_Paper45.pdf.  it seems that the result of that paper is use results_medium-8c4h.csv and results_medium-8c4h_ref.csv

**Comment by seb-h2o** [comment]
@ajoeajoe for some of the larger datasets like Airlines, we also had issues with `sklearn.RandomForest`: cf. https://github.com/openml/automlbenchmark/blob/master/reports/results_large-8c4h_ref.csv

If you check the `params` column, you'll notice that due to memory issues with our default params (`n_jobs`= all_cpus, `n_estimators=2000` ), those params had to be progressively adjusted for the larger datasets in order to obtain a reference result.

We didn't have this issue for small and medium datasets though except for `Helena`:
https://github.com/openml/automlbenchmark/blob/master/reports/results_medium-8c4h_ref.csv

**Comment by seb-h2o** [comment]
@ajoeajoe for some of the larger datasets like Airlines, we also had issues with `sklearn.RandomForest`: cf. https://github.com/openml/automlbenchmark/blob/master/reports/results_large-8c4h_ref.csv

If you check the `params` column, you'll notice that due to memory issues with our default params (`n_jobs`= all_cpus, `n_estimators=2000` ), those params had to be progressively adjusted for the larger datasets in order to obtain a reference result.

We didn't have this issue for small and medium datasets though except for `Helena`:
https://github.com/openml/automlbenchmark/blob/master/reports/results_medium-8c4h_ref.csv

**Comment by ajoeajoe** [comment]
ok  thx
