### ISSUE TITLE
benchmark_datasets.html page not accessible

### ISSUE THREAD

**Issue by yashgarg1232** [openml/automlbenchmark#493]
The following link is not accessible

https://openml.github.io/automlbenchmark/benchmark_datasets.html

If the URL changes, unable to trace the new path.

**Comment by PGijsbers** [comment]
Sorry for the inconvenience! We updated our site and that page is no longer available. Its content is still in this repository: https://github.com/openml/automlbenchmark/blob/master/docs/benchmark_datasets.md
We probably should add a redirect/way to access the old site.

Where did you find this link? Was it from the 2019 paper, or did you come across it elsewhere?

**Comment by PGijsbers** [comment]
There is now a redirect to the readme.
