### ISSUE TITLE
AMLB stuck at loading data

### ISSUE THREAD

**Issue by BingzhaoZhu** [openml/automlbenchmark#506]
The dataloader of AMLB can hang for a long time for simple examples. The issue seems to be related to [this line](https://github.com/BingzhaoZhu/automlbenchmark/blob/58361150f3214b98241ac7e373eccfe6c3567905/amlb/benchmark.py#L486). 

To reproduce the error, ```python3 runbenchmark.py constantpredictor test test```  and we see the following log (using a aws server in us-east-1, G4dn): 

/usr/bin/python3.8 /home/ubuntu/automlbenchmark/runbenchmark.py constantpredictor test test -f 0 
Running benchmark `constantpredictor` on `test` framework in `local` mode.
Loading frameworks definitions from ['/home/ubuntu/automlbenchmark/resources/frameworks.yaml'].
Loading benchmark constraint definitions from ['/home/ubuntu/automlbenchmark/resources/constraints.yaml'].
Loading benchmark definitions from /home/ubuntu/automlbenchmark/resources/benchmarks/test.yaml.

-----------------------------------------------------
Starting job local.test.test.kc2.0.constantpredictor.
Assigning 2 cores (total=8) for new task kc2.
Assigning 25549 MB (total=31641 MB) for new kc2 task.
---start loading data---
[MONITORING] [python3.8 [105386]] CPU Utilization: 86.4%
[MONITORING] [python3.8 [105386]] Memory Usage: 12.8%
[MONITORING] [python3.8 [105386]] Disk Usage: 29.9%
[MONITORING] [python3.8 [105386]] CPU Utilization: 2.0%
[MONITORING] [python3.8 [105386]] Memory Usage: 12.8%
[MONITORING] [python3.8 [105386]] Disk Usage: 29.9%
[MONITORING] [python3.8 [105386]] CPU Utilization: 0.2%
[MONITORING] [python3.8 [105386]] Memory Usage: 12.8%
[MONITORING] [python3.8 [105386]] Disk Usage: 29.9%
[MONITORING] [python3.8 [105386]] CPU Utilization: 2.9%
[MONITORING] [python3.8 [105386]] Memory Usage: 12.9%
[MONITORING] [python3.8 [105386]] Disk Usage: 29.9%

**Comment by joaquinvanschoren** [comment]
Thanks for reporting the issue. It is the same issue as reported here: https://github.com/openml/openml-python/issues/1181
There is a monkey patch available in case it's urgent. 

We hope to resolve the issue asap.

**Comment by joaquinvanschoren** [comment]
Dataset download is restored.
