### ISSUE TITLE
about overfit or not

### ISSUE THREAD

**Issue by ajoeajoe** [openml/automlbenchmark#51]
How can I interpret the result, for example , run 10 folds using autosklearn train on  adult dataset , and config max_runtime_seconds  one hour, may be two hour per fold, How can I know if this result overfit or not as i have no idea of learning curve?

**Comment by seb-h2o** [comment]
@ajoeajoe The result score is computed against predictions on a `test` set.
The only way to know if the autosklearn model was overfitting would be by analyzing predictions during the training/fitting phase, and possibly comparing them with those `test` predictions.
If you want more information about how the various `automl` tools pick the final model, I don't think that `automlbenchmark` is currently the right app for this: although we could also extract more information like the way we extract trained models from autosklearn for example: https://github.com/openml/automlbenchmark/blob/master/frameworks/autosklearn/exec.py#L85

**Comment by PGijsbers** [comment]
> If you want more information about how the various automl tools pick the final model

You can also find links to the original papers on the [site](https://openml.github.io/automlbenchmark/automl_overview.html).

We'd like to collect more information on the optimization process of each tool, such as which models they considered. Unfortunately there is no standardized way of collecting this information (most tools don't even provide documentation for this), so we left it out of scope for now. Anytime performance is also not supported for all tools, in particular those that only build their final model after search (e.g. `auto-sklearn`.

**Comment by seb-h2o** [comment]
Closing this ticket.
We may later provide more information in the results to help with their interpretation, but it needs to be defined more precisely.
