### ISSUE TITLE
Does H2OAutoML run in venv?

### ISSUE THREAD

**Issue by sedol1339** [openml/automlbenchmark#595]
Hello! `frameworks/H2OAutoML/` folder contains `setup.sh` that seems to install packages in a separate venv. However, `exec.py` does not use the `run_in_venv` method. So, the venv is created but not used?

**Comment by PGijsbers** [comment]
`exec.py` defines a run function which may or may not be called from a separate process with its own virtual environment. Whether not it is executed in a virtual environment depends on the `run` function of `__init__`.py. As you can see [here](https://github.com/openml/automlbenchmark/blob/386cfb66baa576ca9891ca18007c8d298380da3e/frameworks/H2OAutoML/__init__.py#L23), the `run` function from `exec.py` will be executed from `run_in_venv`.

**Comment by sedol1339** [comment]
Understood, thank you!
