### ISSUE TITLE
Multiple predictions in a single exec.py

### ISSUE THREAD

**Issue by sedol1339** [openml/automlbenchmark#598]
Hello! My model has several stages, and hence exec.py produces several predictions. I would like to evaluate them all. How to do this? I see that run_in_venv should return only a single prediction for every test sample, is there a way to bypass this limitation?

**Comment by PGijsbers** [comment]
While you cannot have the automl benchmark software evaluate the predictions at the different stages, you can definitely store those predictions and write your own code to load and evaluate them. For example, [auto-sklearn](https://github.com/openml/automlbenchmark/blob/master/frameworks/autosklearn/exec.py) saves a number of models. Anything written to the subdirectory generated by `from frameworks.shared.callee import output_subdir` will be stored and available after the benchmark run. By convention we use a `_save_artifacts` script parameter to specify which information the integrated framework should store (in addition to the minimum that are returned by the `results(...)` call).

**Comment by sedol1339** [comment]
Thank you!
