### ISSUE TITLE
More detailed results from the paper

### ISSUE THREAD

**Issue by sedol1339** [openml/automlbenchmark#599]
Hello! Can you please provide metrics for each fold from the paper? Because I currently have my results only for 1 fold, and cannot directly compare my 1 fold results with 10 fold average results from the paper.

**Comment by PGijsbers** [comment]
https://test.openml.org/amlb/ have all experiment artifacts. Please refer to the `*_cleaned.csv` files. We will also be releasing a new set of experimental results very soon.
