### ISSUE TITLE
Broken link (interactive visualization tool)

### ISSUE THREAD

**Issue by CarachinoAlessio** [openml/automlbenchmark#607]
Hello there!
It's been days I've been trying to access to the visualization tool on this [site](https://compstat-lmu.shinyapps.io/AutoML-Benchmark-Analysis/ ).
Unfortunately, it seems like it's not working.

Is the link correct? I found it on the [index page](https://openml.github.io/automlbenchmark/index.html) that appears on the README file.

Here is a screenshot with the error (bottom left of the image).
<img width="1245" alt="screenshot" src="https://github.com/openml/automlbenchmark/assets/73645335/cc37dc13-fdc0-4f8c-b6f7-7308cc9eb36c">

**Comment by PGijsbers** [comment]
Thanks for the report! The tool is a little outdated, and we're currently working on a new tool to fix that (migrating from R to Python at the same time). However, I was under the impression that the old results were at least still available there.

@Coorsaa is it easy for you to figure out why it's not running, and turn it back on for now?

**Comment by CarachinoAlessio** [comment]
In the meantime... thank you for your quick feedback :)
