### ISSUE TITLE
Support for OpenML Studies

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#61]
As mentioned in https://github.com/openml/automlbenchmark/issues/17 and https://github.com/openml/automlbenchmark/pull/57, now that the benchmark definition file format is very simple, we could create a small script converting [OpenML Studies](https://docs.openml.org/#studies-under-construction) into a benchmark definition to make it easier to manage definitions and maybe as well to upload results.

**Comment by PGijsbers** [comment]
@ja-thomas did you ever manage to upload the full list of tasks we considered previously? If so, what is the study id?

The studies I created are 218 (study - collection of tasks), and 226 (suite - a collection of runs).
