### ISSUE TITLE
Time series forecasting support for FEDOT

### ISSUE THREAD

**Issue by Lopa10ko** [openml/automlbenchmark#610]
As a demonstration of the concept for time-series benchmarking #494, more autoML frameworks capable of predicting time series should be provided with benchmarking support. 

This issue is dedicated to implementing time-series benchmarking support for the [FEDOT](https://github.com/aimclub/FEDOT) framework.

**Comment by PGijsbers** [comment]
@shchur would you be willing to oversee this, in case any questions come along? I'm pressed for time at the moment and I am sure you are more familiar with the relevant parts of the code to begin with :)

**Comment by shchur** [comment]
Apologies for a late reply, I just came back from a vacation today. This week is rather packed for me, I will try to review the PR next week.

**Comment by shchur** [comment]
@Lopa10ko sorry for the delay, I have left a few comments on the PR.
