### ISSUE TITLE
'NoResultError' raised by FLAML Framework During Benchmark Execution

### ISSUE THREAD

**Issue by tomsz92161** [openml/automlbenchmark#623]
Hello,

I have just installed AutoML Benchmarck in an environment running Python 3.9.17. However, when I execute the command `python runbenchmark.py flaml`, I encounter the following error:

NoResultError: `best_iteration` is only defined when early stopping is used.

Is there a workaround to resolve this issue?

Thank you.

[error_traceback.txt](https://github.com/openml/automlbenchmark/files/15469087/error_traceback.txt)

**Comment by israel-cj** [comment]
I had the same problem; it was related to flaml version 1.2.4 being used. 
Force the latest version:
`python runbenchmark.py flaml:latest`

**Comment by PGijsbers** [comment]
I'll look into what exactly is causing this issue, but in the meanwhile, I hope @israel-cj's fix works for you!

**Comment by israel-cj** [comment]
For me, it worked when I force (`-s force`) the setup mode as well (you only need to do this once):
`python runbenchmark.py flaml:latest -s force`

**Comment by PGijsbers** [comment]
A couple of different issues were at play. In short:

 - Following a regular setup which install `flaml==1.2.4`, you can downgrade xgboost with `frameworks/flaml/venv/bin/python -m pip install "xgboost<2"` and it should work.
 - #626 has fixes that should allow both old and new versions of flaml to be installed and evaluated with the automl benchmark. Tested with Python 3.9.16.
 
 Thanks for your patience. Please let me know if this resolves your issues.
