### ISSUE TITLE
Upgrade frameworks to their latest stable version

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#84]
- autosklean: 0.6.0
- TPOT: 0.11.1
- H2O: 3.30.x
...

**Comment by franchuterivera** [comment]
Hello, I am working to create a pull request to move to autosklean==0.6.0 (working with the autosklearn developer to do so).
I guess it makes sense not to duplicate effort...

**Comment by sebhrusen** [comment]
@franchuterivera sure, thanks for that. Nothing started on my side. Please refer to this ticket once you create your PR.
