### ISSUE TITLE
benchmark.py save logs

### ISSUE THREAD

**Issue by PGijsbers** [openml/automlbenchmark#9]
Save logs of amazon instances to disk.

**Comment by PGijsbers** [comment]
Largely done, but from a few test runs it seems that very rarely not all of the log is received properly. This is probably a separate issue.

Further improvements left to be done: save only output produced by us, or at the very least nothing before or after output produced by us (e.g. discard startup output).

**Comment by seb-h2o** [comment]
@PGijsbers what kind of logs are we talking about here?
currently, we save benchmark logs (everything logged by `automl` and `frameworks` modules) at DEBUG level, and all others (this includes 3rd parties libraries, including the benchmarked tools themselves) at INFO level: this generates enough information without being too large. Also, log levels can be changed quite easily if needed.

**Comment by seb-h2o** [comment]
I've been thinking about saving toolset logs as well when it can be done easily.

**Comment by seb-h2o** [comment]
As of version 1.0, benchmark app logs generated on EC2 instances (using docker or not) are saved to s3 and retrieved locally once the benchmark job is completed.
Closing this issue.
