### ISSUE TITLE
Problem With Singularity Pull Command

### ISSUE THREAD

**Issue by franchuterivera** [openml/automlbenchmark#90]
There is an issue with amlb/singularity.py, likely produced by a name change.

I think when doing the merge, you guys saw fit to rename:

def _container_image_name(self, branch=None, **return_docker_name**=False):

to be:

image_name(cls, framework_def, branch=None, **as_docker_image**=False, **kwargs):

We need to replace all occurrences of return_docker_name to be as_docker_image. For instance 

https://github.com/openml/automlbenchmark/blob/2842df7ada191d0a0e9a7d7ac9096439714b029c/amlb/singularity.py#L130

As of now, pulling from a singularity command fails and is masked by the exception catching.

**Comment by PGijsbers** [comment]
Looks like it probably got introduced by #89 @sebhrusen

**Comment by sebhrusen** [comment]
@franchuterivera I'm really sorry, I had to make a quick fix yesterday because the singularity changes broke the AWS support when using docker image on EC2.
I should have retested singularity properly.
Fixing asap.

**Comment by sebhrusen** [comment]
fixed.
@franchuterivera if you have any idea about my comment https://github.com/openml/automlbenchmark/pull/91#discussion_r404910131
It would be a useful improvement, thx
