### ISSUE TITLE
Singularity PWD for docker conversion

### ISSUE THREAD

**Issue by franchuterivera** [openml/automlbenchmark#92]
### What?
One of the features of singularity is to convert docker images to singularity images. This is useful for us, because the automlbenchmarck team generates docker images which we can use in our cluster machines that only have singularity.

Seems like there is a bug when translating the docker image to a singularity image, documented here https://github.com/sylabs/singularity/issues/380

### Request:
 add a --pwd option to singularity
from:
https://github.com/openml/automlbenchmark/blob/e2d8ec3f38c3cb67af2cb0f52045d25c5def0806/amlb/singularity.py#L97
to:
 cmd = (
            "singularity run **--pwd /bench** {options} "
      

### Why wasn't this seen before?
I notice this behavior when adding a new framework using the virtual environment for python based frameworks. I don't know what exactly triggers the WORKDIR directive of docker not to be followed by singularity, but the --pwd option is a robust WA to be transparent to this problem.

I am sorry for the trouble, this wasn't seen before in our testing. I can create a push request for this if you want. Please let me know.

**Comment by sebhrusen** [comment]
> I can create a push request for this if you want
@franchuterivera please do, thanks

**Comment by sebhrusen** [comment]
@franchuterivera also having error when building a singularity image: symlink creation issue apparently, does it ring a bell?
Note that I'm running singularity inside a virtualbox on macOS, so it may only with this particular setup.

```
INFO:    Running post scriptlet
+ DEBIAN_FRONTEND=noninteractive
+ apt-get update
+ apt-get -y install apt-utils dialog locales
debconf: delaying package configuration, since apt-utils is not installed
+ apt-get -y install curl wget unzip git
+ apt-get -y install python3 python3-pip python3-venv
+ pip3 install -U pip
+ SPIP=pip3
+ SPY=python3
+ PYTHONUTF8=1
+ PYTHONIOENCODING=utf-8
+ LANG=C.UTF-8
+ LC_ALL=C.UTF-8
+ cd /bench
+ python3 -m venv venv
Unable to symlink '/usr/bin/python3' to '/bench/venv/bin/python3'
+ PIP=/bench/venv/bin/pip3
+ PY=/bench/venv/bin/python3
+ /bench/venv/bin/pip3 install -U pip
/tmp/rootfs-4a3e56c3-79cc-11ea-ad77-0800272be0ec/.build-script-post: 28: /tmp/rootfs-4a3e56c3-79cc-11ea-ad77-0800272be0ec/.build-script-post: /bench/venv/bin/pip3: not found
FATAL:   failed to execute %post proc: exit status 127
FATAL:   While performing build: while running engine: while running /usr/local/libexec/singularity/bin/starter: exit status 255
```

**Comment by franchuterivera** [comment]
I have not faced this problem before. Please let the know what you did
exactly.

Also, I am testing every single framework with singularity after the push,
so I would probably do a PR on Friday to make sure all works.

I am having some issues with oboe due to some dependencies, but I don't
think it's singularity related.

I can also include a fix, if needed, for this issue you are seeing....

Seb <notifications@github.com> schrieb am Mi., 8. Apr. 2020, 21:36:

**Comment by sebhrusen** [comment]
@franchuterivera I updated many frameworks today.
oboe should work now, please rebase from `master`.

For the error above, I just ran
```
(venv) vagrant@vagrant:~/repos/automlbenchmark$ python runbenchmark.py tpot -m singularity -s force
```
don't worry, probably an issue due to the combination macOS+vagrant+singularity, I don't see why it would complain about symlink otherwise if it's usually working on Linux.
