### ISSUE TITLE
Add AutoGluon framework

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#93]
https://github.com/awslabs/autogluon
Last stable version seems to be v0.0.6.

@Innixma do you have any concern if we want to make Autogluon publicly available in the benchmark application?

**Comment by Innixma** [comment]
No concern, I think this would be great!

We actually used automlbenchmark for our paper: https://arxiv.org/pdf/2003.06505.pdf

I have a working version of AutoGluon in my fork of the repo: https://github.com/Innixma/automlbenchmark

I've only tested it on the local version, and its based on a fairly outdated version of automlbenchmark, so you may have to rework parts of it.

One note: At least in local, this fix needs to be added for AG to work, as AG imports numba and numba must be imported prior to some of the imports that occur in automlbenchmark: https://github.com/Innixma/automlbenchmark/blob/master/amlb/logger.py#L9

**Comment by sebhrusen** [comment]
@Innixma great!
I'll use your fork to make the integration easier, will only create the default `autogluon`, it's then possible to create additional frameworks purely declaratively in a local `framework.yaml`.

Same for the `auto_stack=True`: our policy for AutoML tools is to integrate then and provide a default definition in `resources/frameworks.yaml` with only the default parameters defined by the AutoML tool itself.
The integration only set parameters related with time limit and resources (memory, cpu...) if any to ensure that the toolkit provides a result after the time limit.
But as mentioned above, we also integrate those in such a way that user can activate feature declaratively in a custom `frameworks.yaml`:
```
autogluon_autostack:
   extends: autogluon
   params:
       auto_stack: true

autogluon_noknn:
    extends: autogluon
    params:
         #your noknn params here
```
Those params are then automatically included in the benchmark results file, which also helps to analyze results.

Also, there have been some improvements to the benchmark app since, and AutoGluon will be able to run in its own process in a dedicated virtualenv, so it should make the setup easier and the `numba` fix unnecessary.

**Comment by Innixma** [comment]
Please use https://github.com/Innixma/automlbenchmark/tree/autogluon-test for the latest version, I made some recent changes to reduce the amount of internal AutoGluon functions being used in the wrapper.

The declarative functionality sounds great, definitely easier than what I was doing!
